### ISSUE TITLE
Multiple services with mulitple Routing not working

### ISSUE THREAD

**Issue by ssboopathi** [MohamedFawzy/hotels#2]
I have used on your files. It's working fine. I have added the extra two services in the docker-compose.yml file. I have removed the volume_from in all the services. I have removed the mongodb service in the docker-compose file.

```
microservice_first_hotels_fpm:
        build: ./microservices/first_hotels/php-fpm/
        links:
            - autodiscovery
        ports:
            - 9001:9000
        environment:
            - BACKEND=microservice-hotels-nginx
            - CONSUL=autodiscovery

microservice_second_hotels_fpm:
        build: ./microservices/second_hotels/php-fpm/
        links:
            - autodiscovery
        ports:
            - 9002:9000
        environment:
            - BACKEND=microservice-hotels-nginx
            - CONSUL=autodiscovery

microservice_third_hotels_fpm:
        build: ./microservices/third_hotels/php-fpm/
        links:
            - autodiscovery
        ports:
            - 9003:9000
        environment:
            - BACKEND=microservice-hotels-nginx
            - CONSUL=autodiscovery

    microservice_hotels_nginx:
        build: ./microservices/nginx/
        links:
            - autodiscovery
        environment:
            - BACKEND=microservice-first-hotels-fpm
            - BACKEND=microservice-second-hotels-fpm
            - BACKEND=microservice-third-hotels-fpm
            - CONSUL=autodiscovery
        ports:
            - 8081:80
            - 9091:9090
```
I have changed the folder structure. I have added below the folder structure.
```
hotels
    |_ source
        |_ index.php
        |_ first_hotel
             |_ Lumen Files
        |_ second_hotel
             |_ Lumen Files
        |_ third_hotel
             |_ Lumen Files
    |_ docker
        |_ autodiscovery
             |_ Dockerfile
        |_ microservices
             |_ nginx
                    |_ config
                            |_  containerpilot.json
                            |_  nginx
                                   |_  nginx.conf.ctmpl
                    |_ Dockerfile
                    |_ scripts
                            |_  reload.sh
                            |_  sensor.sh
             |_ first_hotels
                    |_ php-fpm
                            |_  config
                                   |_  containerpilot.json
                            |_  Dockerfile
                            |_  scripts
                                   |_  reload.sh
             |_ second_hotels
                    |_ php-fpm
                            |_  config
                                   |_  containerpilot.json
                            |_  Dockerfile
                            |_  scripts
                                   |_  reload.sh
             |_ third_hotels
                    |_ php-fpm
                            |_  config
                                   |_  containerpilot.json
                            |_  Dockerfile
                            |_  scripts
                                   |_  reload.sh

```
I have changed the microservice name in the containerpilot.json file for first_hotels, second_hotels, and third_hotels. 

Microservices inside the nginx folder is there. That folder having the nginx.conf.ctmpl file. This file I have changed the server.
```
server {
    root /var/www/html/source;//I have changed the root url
   // I have added the following lines.
       location ^~ /first_hotels {
            root /var/www/html/source/first_hotels/public;
        }

        location ^~ /second_hotels {
            root /var/www/html/source/second_hotels/public;
        }

        location ^~ /third_hotels {
            root /var/www/html/source/third_hotels/public;
        }
}

```

Now I have used the command. `docker-compose down`

Again I have started the compose command.

`docker-compose up --build -d`

I have checked in browser with consul UI. It's working fine.

![Screenshot from 2019-04-30 17-26-59](https://user-images.githubusercontent.com/49145557/56960891-df18d800-6b6f-11e9-9fa1-a5d9ea1ae735.png)

I have checked on the URL. It's showing **404 not found** error.

![Screenshot from 2019-04-30 17-23-23](https://user-images.githubusercontent.com/49145557/56959930-d1158800-6b6c-11e9-90b3-c901627fa5d5.png)
